from Source import (QApplication,PhotoLib, image)
import sys

__init__ = QApplication(sys.argv) # APPLICATION BUILD BEFORE PIXMAP

DELETE = image( PhotoLib.get(1) )
PEN_L = image( PhotoLib.get(2) )
MAIL = image( PhotoLib.get(3) )
PDF = image( PhotoLib.get(4) )
SCOPE = image( PhotoLib.get(5) )
GENERATE_L = image( PhotoLib.get(6) )
TIME_TABLE = image( PhotoLib.get(7) )
PROFESSOR = image( PhotoLib.get(8) )
SUBJECT = image( PhotoLib.get(9) )
RECORD = image( PhotoLib.get(10) )
USER_D = image( PhotoLib.get(11) )
USER_L = image( PhotoLib.get(12) )
GEAR_L = image( PhotoLib.get(13) )
GEAR_D = image( PhotoLib.get(14) )
WHAT_L = image( PhotoLib.get(15) )
WHAT_D = image( PhotoLib.get(16) )
PEN_D = image( PhotoLib.get(17) )
MARK_L = image( PhotoLib.get(18) )
MARK_D = image( PhotoLib.get(19) )
GENERATE_D = image( PhotoLib.get(20) )
NEXT_L = image( PhotoLib.get(25) )
NEXT_D = image( PhotoLib.get(26) )
XLSX = image( PhotoLib.get(27) )
LOGIN = image( PhotoLib.get(29) )
ACCOUNT = image( PhotoLib.get(30) )
EYE_CLOSED = image( PhotoLib.get(31) )
EYE_OPENED = image( PhotoLib.get(32) )
KEY = image( PhotoLib.get(33) )
SECURE_D = image( PhotoLib.get(34) )
SECURE_L = image( PhotoLib.get(35) )
KEYBOARD_D = image( PhotoLib.get(36) )
KEYBOARD_L = image( PhotoLib.get(37) )
UI_L = image( PhotoLib.get(38) )
UI_D = image( PhotoLib.get(39) )
TICK_D = image( PhotoLib.get(40) )
TICK_L = image( PhotoLib.get(41) )
BACK_D = image( PhotoLib.get(42) )
BACK_L = image( PhotoLib.get(43) )
SCOPE_L = image( PhotoLib.get(44) )

SCHOLAR = PhotoLib.get(28) # PIXMAP
